#!/usr/bin/env bash
# ****************************************************
#
#   Cask
#
# ****************************************************

brew tap caskroom/cask
brew tap caskroom/versions

applications=(
  aerial
  abstract
  adobe-creative-cloud
  android-studio
  bartender
  basecamp
  bettertouchtool
  caffeine
  dash
  dashlane
  dropbox
  firefox
  google-chrome
  github-desktop
  hazel
  iconjar
  istat-menu
  iterm2
  marvel
  muse
  moom
  nucleo
  oh-my-zsh
  principle
  sketch
  sketchup
  spotify
  transmit
  visual-studio-code-insiders
  zoomus
)

for application in ${applications[@]}; do
  brew cask install $application 2> /dev/null
done

# ----------------------------------------------------
#   Disabled
# ----------------------------------------------------

# arq
# atom
# atom-beta
# balsamiq-mockups
# bitbar
# cheatsheet
# docker
# drobo-dashboard
# duet
# focus
# fontbase
# github-desktop
# gitscout
# google-drive
# hyper
# iconjar
# instacast
# kap
# keepingyouawake
# liteicon
# macvim
# mamp
# michaelvillar-timer>
# mongodb-compass
# noun-project
# paw
# postgres
# rocket
# screenflow
# screenhero
# shortcat
# skyfonts
# sublime-text
# superduper
# toggldesktop
# tower2
# twitch
# visual-studio-code-insiders
# vlc
